name: Update Contribution Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download graph
        run: |
          mkdir -p dist

          curl -fL \
            "https://gh.crafter.run/SatyamPrakash09?theme=dark&cols=80" \
            -o dist/contribution-graph.svg

          echo "Generated file:"
          ls -lh dist/contribution-graph.svg

      - name: Publish graph
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
